### ISSUE TITLE
KeyError for TS26510_Maf_Provisioning_ProvisioningSessions.yaml while generating lua code for REL-18 tag: TSG104-Rel18

### ISSUE THREAD

**Issue by JacekWentland** [telekom/OpenAPI-Dissector#3]
While generating the lua code following error is seen:
`    pathspec = paths[pathspec['$ref']]
KeyError: 'TS26510_Maf_Provisioning_ProvisioningSessions.yaml#/paths/~1provisioning-sessions~1%7bprovisioningSessionId%7d'
`
The error goes away when moved to TSG103-Rel18 (the problematic files are not there).
I have not investigated what the problem was caused by. The diagnostic is not clear as to whether the problem is in the generator code or in the 3gpp spec. 
[OpenAPI-gen_problem.log](https://github.com/user-attachments/files/17028965/OpenAPI-gen_problem.log)

**Comment by lukas2511** [comment]
Mhmh... there are some weird things happening in the Rel-18 files. The major issue happening here was that url-encoded parts of references now had mixed case. Since the generator script only uses a dictionary lookup it wasn't able to find those specs and for now that results in a hard crash. Other than that some URLs now seem to be pre-encoded, which didn't make much sense either... 

All the issues seem to be related to Maf/Mas documents, which seem to still be in a very rough state. I'm guessing this would be resolved over time, but I've just pushed deff9c461ccb89add167dcbdd8c3089b6c64594b as a workaround for this. The changes make the generator work with unquoted paths instead of quoted ones, meaning the mixed case issues should be fully resolved. I've build test-specs using the Rel 15, 16, 17 and 18 branches without any issues.
